import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const SF = localFont({
  src: "./fonts/SF-Compact-Text-Medium.otf",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${SF.className} h-full antialiased bg-black`}>
      <body className="min-h-full flex flex-col w-full h-dvh bg-black">
        {children}
      </body>
    </html>
  );
}
