import type { Metadata } from "next";
import { Geist } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { cn } from "@/lib/utils";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

const SF = localFont({
  src: "./fonts/SF-Compact-Text-Medium.otf",
});

export const metadata: Metadata = {
  title: "Grow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        "bg-black",
        SF.className,
        "font-sans",
        geist.variable,
      )}
    >
      <body className="min-h-full flex flex-col w-full h-dvh bg-black">
        {children}
      </body>
    </html>
  );
}
